apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openhack-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-tripviewer
            port:
              number: 80
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: svc-userprofile
            port:
              number: 80
      - path: /api/user-java
        pathType: Prefix
        backend:
          service:
            name: svc-user-java
            port:
              number: 80
      