apiVersion: v1
kind: Pod
metadata:
  labels:
    run: poiapi
  name: poiapi
spec:
  containers:
  - image: registryhcv3795.azurecr.io/openhack/poiapi:latest
    name: poiapi
    env:
     - name: WEB_SERVER_BASE_URI
       value: 'http://0.0.0.0'
     - name: WEB_PORT
       value: '8080'
     - name: ASPNETCORE_ENVIRONMENT
       value: "Production"
    envFrom:
    - secretRef:
        name: sqldbsecret
    ports:
    - containerPort: 80

