apiVersion: v1
kind: Service
metadata:
  name: svc-tripsapi
spec:
  selector:
    run: tripsapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443