apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tripviewer
  name: tripviewer
spec:
  containers:
  - image: registryhcv3795.azurecr.io/openhack/tripviewer:latest
    name: tripviewer
    env:
      - name: USERPROFILE_API_ENDPOINT
        value: "http://svc-userprofile.web.svc.cluster.local"
      - name: TRIPS_API_ENDPOINT
        value: "http://svc-tripsapi.api.svc.cluster.local"
