apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tripsapi
  name: tripsapi
spec:
  containers:
  - image: registryhcv3795.azurecr.io/openhack/tripsapi:latest
    name: tripsapi
    env:
    - name: PORT
      value: '80'
    - name: OPENAPI_DOCS_URI
      value: 'http://localhost'
    - name: DEBUG_LOGGING
      value: 'true'
    - name: ASPNETCORE_ENVIRONMENT
      value: "Production"
    envFrom:
    - secretRef:
        name: sqldbsecret
    ports:
    - containerPort: 80