apiVersion: v1
kind: Pod
metadata:
  labels:
    run: user-java
  name: user-java
spec:
  containers:
  - image: registryhcv3795.azurecr.io/openhack/user-java:latest
    name: user-java
    envFrom:
    - secretRef:
        name: sqldbsecret
    ports:
    - containerPort: 80
