kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-user-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-user-full-access
subjects:
- kind: Group
  namespace: web
  name: c9a79ff7-11ff-4eab-b668-2a198170e019